### ISSUE TITLE
Error DataServ-Client.exe  Please help my!

### ISSUE THREAD

**Issue by Ombc** [Storj/driveshare.org#22]
Hello guys can u help my please i want to press on the Start button of the gui

i have the newest gui downloaded and python installed and i don't get it working

i have a macbook too there everything work's perfect but i need it on my windows too

hope you can help my guys and this is the error code

Traceback (most recent call last):
  File "dataserv-client", line 6, in <module>
  File "dataserv_client\cli.pyo", line 4, in <module>
  File "dataserv_client\api.pyo", line 7, in <module>
  File "storjnode\__init__.pyo", line 3, in <module>
  File "storjnode\network\__init__.pyo", line 1, in <module>
  File "storjnode\network\node.pyo", line 12, in <module>
  File "storjnode\network\server.pyo", line 8, in <module>
  File "kademlia\network.pyo", line 8, in <module>
  File "twisted\internet\reactor.pyo", line 39, in <module>
  File "twisted\internet\selectreactor.pyo", line 196, in install
  File "twisted\internet\selectreactor.pyo", line 72, in __init__
  File "twisted\internet\base.pyo", line 499, in __init__
  File "twisted\internet\posixbase.pyo", line 284, in installWaker
  File "twisted\internet\posixbase.pyo", line 74, in __init__
  File "socket.pyo", line 191, in __init__

**Comment by littleskunk** [comment]
Please add the exception message as well.

**Comment by Ombc** [comment]
wat do you mean? exception message?

**Comment by littleskunk** [comment]
Please copy everything that follows the lines you already added.

**Comment by Ombc** [comment]
yeah okay but my computer language is not english i hope that is not a problem

**Comment by Ombc** [comment]
C:\Users\Gebruiker>cd C:\Users\Gebruiker\Downloads\dataserv-client

C:\Users\Gebruiker\Downloads\dataserv-client>dataserv-client.exe config
Traceback (most recent call last):
  File "dataserv-client", line 6, in <module>
  File "dataserv_client\cli.pyo", line 4, in <module>
  File "dataserv_client\api.pyo", line 7, in <module>
  File "storjnode\__init__.pyo", line 3, in <module>
  File "storjnode\network\__init__.pyo", line 1, in <module>
  File "storjnode\network\node.pyo", line 12, in <module>
  File "storjnode\network\server.pyo", line 8, in <module>
  File "kademlia\network.pyo", line 8, in <module>
  File "twisted\internet\reactor.pyo", line 39, in <module>
  File "twisted\internet\selectreactor.pyo", line 196, in install
  File "twisted\internet\selectreactor.pyo", line 72, in __init__
  File "twisted\internet\base.pyo", line 499, in __init__
  File "twisted\internet\posixbase.pyo", line 284, in installWaker
  File "twisted\internet\posixbase.pyo", line 74, in __init__
  File "socket.pyo", line 191, in __init__
socket.error: [Errno 10106] De aangevraagde serviceprovider kan niet worden gela
den of ge´nitialiseerd

C:\Users\Gebruiker\Downloads\dataserv-client>

**Comment by littleskunk** [comment]
Error 10106 is a problem with your system and nothing we can fix in dataserv-client. Please check your network connection and your firewall.

Sorry I have to close this issue. It is the wrong repository and no bug. Better place for this would be slack. As soon as the invite bot is available again (https://github.com/Storj/storj.io/issues/69)

**Comment by Ombc** [comment]
what must i do now than??

**Comment by littleskunk** [comment]
Fix the problem with your network connection / wrong firewall settings. Join us on slack if you need help. Invite bot is working now.
